# Generated by Django 4.1 on 2022-08-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_gallery', to='cinema.gallerymodel')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_main_image', to='cinema.gallerymodel')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsPromoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('URL', models.URLField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_promo_gallery', to='cinema.gallerymodel')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_promo_main_image', to='cinema.gallerymodel')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
            options={
                'verbose_name': 'Новости и Промо',
                'verbose_name_plural': 'Новости и Промо',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_phone', models.CharField(max_length=20)),
                ('second_phone', models.CharField(max_length=20)),
                ('seo_text', models.TextField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('coords', models.CharField(max_length=50)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_logo', to='cinema.gallerymodel')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
