# Generated by Django 4.1 on 2022-08-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_hallmodel_banner_image_alter_hallmodel_cinema_and_more'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='coords',
            field=models.CharField(max_length=50, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_logo', to='cinema.gallerymodel', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок'),
        ),
        migrations.AlterField(
            model_name='mainpagemodel',
            name='first_phone',
            field=models.CharField(max_length=20, verbose_name='Первый телефон'),
        ),
        migrations.AlterField(
            model_name='mainpagemodel',
            name='second_phone',
            field=models.CharField(max_length=20, verbose_name='Второй телефон'),
        ),
        migrations.AlterField(
            model_name='mainpagemodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок'),
        ),
        migrations.AlterField(
            model_name='mainpagemodel',
            name='seo_text',
            field=models.TextField(verbose_name='СЕО текст'),
        ),
        migrations.AlterField(
            model_name='newspromomodel',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='newspromomodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='newspromomodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_promo_gallery', to='cinema.gallerymodel', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='newspromomodel',
            name='main_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_promo_main_image', to='cinema.gallerymodel', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='newspromomodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='newspromomodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок'),
        ),
    ]
