# Generated by Django 4.1 on 2022-08-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactmodel_pagemodel_remove_pagesmodel_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagemodel',
            name='seo_block',
        ),
        migrations.RemoveField(
            model_name='newspromomodel',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='newspromomodel',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='newspromomodel',
            name='seo_block',
        ),
        migrations.RemoveField(
            model_name='pagemodel',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='pagemodel',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='pagemodel',
            name='seo_block',
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.DeleteModel(
            name='MainPageModel',
        ),
        migrations.DeleteModel(
            name='NewsPromoModel',
        ),
        migrations.DeleteModel(
            name='PageModel',
        ),
    ]
