# Generated by Django 4.1 on 2022-08-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0005_initial'),
        ('pages', '0004_remove_mainpagemodel_seo_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_gallery', to='cinema.gallerymodel', verbose_name='Галерея')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_main_image', to='cinema.gallerymodel', verbose_name='Главное изображение страницы')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsPromoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('URL', models.URLField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_promo_gallery', to='cinema.gallerymodel', verbose_name='Галерея')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_promo_main_image', to='cinema.gallerymodel', verbose_name='Главное изображение')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок')),
            ],
            options={
                'verbose_name': 'Новости и Промо',
                'verbose_name_plural': 'Новости и Промо',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_phone', models.CharField(max_length=20, verbose_name='Первый телефон')),
                ('second_phone', models.CharField(max_length=20, verbose_name='Второй телефон')),
                ('seo_text', models.TextField(verbose_name='СЕО текст')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название кинотеатра')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('coords', models.CharField(max_length=50, verbose_name='Координаты')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_logo', to='cinema.gallerymodel', verbose_name='Лого')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
