# Generated by Django 4.1 on 2022-09-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('repeat_password', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('language', models.BooleanField()),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
