# Generated by Django 4.1 on 2022-08-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nickname', models.CharField(max_length=50, verbose_name='Псевдоним')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50, verbose_name='Адресс')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('repeat_password', models.CharField(max_length=50, verbose_name='Повторить пароль')),
                ('card_number', models.CharField(max_length=50, verbose_name='Номер карты')),
                ('language', models.BooleanField(verbose_name='Язык')),
                ('gender', models.BooleanField(verbose_name='Пол')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.SmallIntegerField(verbose_name='Место')),
                ('reservation', models.BooleanField(verbose_name='Бронирование')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.sessionmodel', verbose_name='Сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usermodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['session'],
            },
        ),
    ]
