# Generated by Django 4.1 on 2022-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='card_number',
            field=models.CharField(max_length=50, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.BooleanField(verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='language',
            field=models.BooleanField(verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='repeat_password',
            field=models.CharField(max_length=50, verbose_name='Повторить пароль'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
