# Generated by Django 4.1 on 2022-08-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nickname', models.CharField(max_length=50, verbose_name='Ник')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('repeat_password', models.CharField(max_length=50, verbose_name='Повторить пароль')),
                ('card_number', models.CharField(max_length=50, verbose_name='Номер карты')),
                ('language', models.BooleanField(verbose_name='Язык')),
                ('gender', models.BooleanField(verbose_name='Пол')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
    ]
