# Generated by Django 4.1 on 2022-08-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кинотеатр')),
                ('description', models.TextField(verbose_name='Описание')),
                ('condition', models.TextField(verbose_name='Условия')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('URL', models.URLField()),
                ('three_D', models.BooleanField(verbose_name='3D')),
                ('two_D', models.BooleanField(verbose_name='2D')),
                ('IMAX', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='HallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('hall_scheme', models.FileField(upload_to='', verbose_name='Схема зала')),
                ('banner_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_banner_image', to='admin_lte.gallerymodel', verbose_name='Баннер')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_lte.cinemamodel', verbose_name='Кинотеатр')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_gallery', to='admin_lte.gallerymodel', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('keywords', models.CharField(max_length=50, verbose_name='Ключевые слова')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'СЕО модель',
                'verbose_name_plural': 'СЕО модели',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField(verbose_name='Стоимость')),
                ('time', models.TimeField(verbose_name='Время')),
                ('three_D', models.BooleanField(verbose_name='3D')),
                ('DBOX', models.BooleanField()),
                ('VIP', models.BooleanField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_lte.filmmodel', verbose_name='Фильм')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_lte.hallmodel', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nickname', models.CharField(max_length=50, verbose_name='Ник')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('repeat_password', models.CharField(max_length=50, verbose_name='Повторить пароль')),
                ('card_number', models.CharField(max_length=50, verbose_name='Номер карты')),
                ('language', models.BooleanField(verbose_name='Язык')),
                ('gender', models.BooleanField(verbose_name='Пол')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.SmallIntegerField(verbose_name='Место')),
                ('reservation', models.BooleanField(verbose_name='Бронирование')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_lte.sessionmodel', verbose_name='Сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_lte.usermodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['session'],
            },
        ),
        migrations.AddField(
            model_name='hallmodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_lte.seomodel', verbose_name='СЕО блок'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='film_gallery', to='admin_lte.gallerymodel', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='main_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='film_main_image', to='admin_lte.gallerymodel', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_lte.seomodel', verbose_name='СЕО блок'),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='banner_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinema_banner_image', to='admin_lte.gallerymodel', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinema_gallery', to='admin_lte.gallerymodel', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinema_logo', to='admin_lte.gallerymodel', verbose_name='Лого'),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_lte.seomodel', verbose_name='СЕО блок'),
        ),
    ]
