# Generated by Django 4.1 on 2022-08-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('rotation_speed', models.TimeField()),
            ],
            options={
                'verbose_name': 'Настройки баннеров',
                'verbose_name_plural': 'Настройки баннеров',
            },
        ),
        migrations.CreateModel(
            name='BannerNewsPromoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='banners.bannerconfigmodel')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_new_promo_image', to='cinema.gallerymodel')),
            ],
            options={
                'verbose_name': 'Баннер новостей и промо',
                'verbose_name_plural': 'Баннера новостей и промо',
            },
        ),
        migrations.CreateModel(
            name='BannerMainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('text', models.CharField(max_length=50)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_main_page_image', to='cinema.gallerymodel')),
            ],
            options={
                'verbose_name': 'Баннер главной страницы',
                'verbose_name_plural': 'Баннер главной страницы',
            },
        ),
        migrations.CreateModel(
            name='BackgroundBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('is_image', models.BooleanField()),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='banners.bannerconfigmodel')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background_banner_image', to='cinema.gallerymodel')),
            ],
            options={
                'verbose_name': 'Фоновый баннер',
                'verbose_name_plural': 'Фоновые баннера',
            },
        ),
    ]
