# Generated by Django 4.1 on 2022-09-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPromoBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Активно')),
                ('URL', models.URLField()),
                ('rotation_speed', models.TimeField(verbose_name='Скорость перехода')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_new_promo_image', to='cinema.gallerymodel', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Баннер новостей и промо',
                'verbose_name_plural': 'Баннера новостей и промо',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MainPageBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Активно')),
                ('URL', models.URLField()),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
                ('rotation_speed', models.TimeField(verbose_name='Скорость перехода')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_main_page_image', to='cinema.gallerymodel', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Баннер главной страницы',
                'verbose_name_plural': 'Баннер главной страницы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет')),
                ('is_image', models.BooleanField(verbose_name='Изображение')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background_banner_image', to='cinema.gallerymodel', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фоновый баннер',
                'verbose_name_plural': 'Фоновые баннера',
                'ordering': ['pk'],
            },
        ),
    ]
