# Generated by Django 4.1 on 2022-08-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_hallmodel_banner_image_alter_hallmodel_cinema_and_more'),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundbannermodel',
            options={'ordering': ['pk'], 'verbose_name': 'Фоновый баннер', 'verbose_name_plural': 'Фоновые баннера'},
        ),
        migrations.AlterModelOptions(
            name='bannerconfigmodel',
            options={'ordering': ['pk'], 'verbose_name': 'Настройки баннеров', 'verbose_name_plural': 'Настройки баннеров'},
        ),
        migrations.AlterModelOptions(
            name='bannermainpagemodel',
            options={'ordering': ['pk'], 'verbose_name': 'Баннер главной страницы', 'verbose_name_plural': 'Баннер главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='bannernewspromomodel',
            options={'ordering': ['pk'], 'verbose_name': 'Баннер новостей и промо', 'verbose_name_plural': 'Баннера новостей и промо'},
        ),
        migrations.AlterField(
            model_name='backgroundbannermodel',
            name='color',
            field=models.CharField(max_length=10, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='backgroundbannermodel',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='banners.bannerconfigmodel', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='backgroundbannermodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background_banner_image', to='cinema.gallerymodel', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='backgroundbannermodel',
            name='is_image',
            field=models.BooleanField(verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bannerconfigmodel',
            name='active',
            field=models.BooleanField(verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='bannerconfigmodel',
            name='rotation_speed',
            field=models.TimeField(verbose_name='Скорость перехода'),
        ),
        migrations.AlterField(
            model_name='bannermainpagemodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_main_page_image', to='cinema.gallerymodel', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bannermainpagemodel',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='bannernewspromomodel',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='banners.bannerconfigmodel', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='bannernewspromomodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_new_promo_image', to='cinema.gallerymodel', verbose_name='Изображение'),
        ),
    ]
