# Generated by Django 4.1 on 2022-08-09 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_backgroundbannermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerconfigmodel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
