# Generated by Django 4.1 on 2022-08-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_hallmodel_banner_image_alter_hallmodel_cinema_and_more'),
        ('banners', '0003_bannerconfigmodel_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerMainPageModel',
            new_name='MainPageBannerModel',
        ),
        migrations.RenameModel(
            old_name='BannerNewsPromoModel',
            new_name='NewsPromoBannerModel',
        ),
    ]
