# Generated by Django 4.1 on 2022-08-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_rename_bannermainpagemodel_mainpagebannermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagebannermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newspromobannermodel',
            name='config',
        ),
        migrations.RemoveField(
            model_name='newspromobannermodel',
            name='image',
        ),
        migrations.DeleteModel(
            name='BackgroundBannerModel',
        ),
        migrations.DeleteModel(
            name='BannerConfigModel',
        ),
        migrations.DeleteModel(
            name='MainPageBannerModel',
        ),
        migrations.DeleteModel(
            name='NewsPromoBannerModel',
        ),
    ]
