# Generated by Django 4.1 on 2022-09-19 08:55

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Фото на фоне', 'Фото на фоне'), ('Просто фон', 'Просто фон')], default='Просто фон', max_length=20)),
                ('image', models.ImageField(null=True, upload_to='images/banners/background')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('condition', models.TextField()),
                ('logo', models.ImageField(upload_to='images/cinemas/logo')),
                ('banner', models.ImageField(upload_to='images/cinemas/banners')),
            ],
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('is_active', models.BooleanField()),
                ('is_2d', models.BooleanField()),
                ('is_3d', models.BooleanField()),
                ('is_imax', models.BooleanField()),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(upload_to='images/films/banners')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('hall_scheme', models.FileField(upload_to='images/halls/hall_schemes')),
                ('banner', models.ImageField(upload_to='images/halls/banners')),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemamodel')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallerymodel')),
            ],
        ),
        migrations.CreateModel(
            name='SeanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField()),
                ('time', models.TimeField()),
                ('is_3d', models.BooleanField()),
                ('is_dbox', models.BooleanField()),
                ('is_vip', models.BooleanField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.filmmodel')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hallmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SeoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_url', models.URLField()),
                ('seo_title', models.CharField(max_length=50)),
                ('seo_keywords', models.CharField(max_length=100)),
                ('seo_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('is_reservation', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seancemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('banner', models.ImageField(upload_to='images/pages/banners')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallerymodel')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery')),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=50)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallerymodel')),
            ],
        ),
        migrations.AddField(
            model_name='hallmodel',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seomodel'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallerymodel'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seomodel'),
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('coordinates', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(upload_to='images/contacts/logos')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seomodel')),
            ],
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallerymodel'),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seomodel'),
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('rotation_speed', models.TimeField()),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallerymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('publication', models.DateField(db_index=True)),
                ('mode', models.CharField(choices=[('NEWS', 'News'), ('PROMO', 'Promo')], max_length=10)),
                ('banner', models.ImageField(upload_to='images/articles/banners')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallerymodel')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seomodel')),
            ],
        ),
    ]
