# Generated by Django 4.1 on 2022-08-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('rotation_speed', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('URL', models.URLField()),
                ('three_D', models.BooleanField()),
                ('two_D', models.BooleanField()),
                ('IMAX', models.BooleanField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='film_gallery', to='cinema.gallerymodel')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='film_main_image', to='cinema.gallerymodel')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
        ),
        migrations.CreateModel(
            name='HallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('hall_scheme', models.FileField(upload_to='')),
                ('banner_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_banner_image', to='cinema.gallerymodel')),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField()),
                ('time', models.TimeField()),
                ('three_D', models.BooleanField()),
                ('DBOX', models.BooleanField()),
                ('VIP', models.BooleanField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.filmmodel')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.hallmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='cinemamodel',
            name='banner_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinema_banner_image', to='cinema.gallerymodel'),
        ),
        migrations.AlterField(
            model_name='cinemamodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinema_gallery', to='cinema.gallerymodel'),
        ),
        migrations.AlterField(
            model_name='cinemamodel',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinema_logo', to='cinema.gallerymodel'),
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.SmallIntegerField()),
                ('reservation', models.BooleanField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.sessionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_gallery', to='cinema.gallerymodel')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_main_image', to='cinema.gallerymodel')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPromoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('URL', models.URLField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_promo_gallery', to='cinema.gallerymodel')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_promo_main_image', to='cinema.gallerymodel')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_phone', models.CharField(max_length=20)),
                ('second_phone', models.CharField(max_length=20)),
                ('seo_text', models.TextField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
        ),
        migrations.AddField(
            model_name='hallmodel',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.cinemamodel'),
        ),
        migrations.AddField(
            model_name='hallmodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_gallery', to='cinema.gallerymodel'),
        ),
        migrations.AddField(
            model_name='hallmodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('coords', models.CharField(max_length=50)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_logo', to='cinema.gallerymodel')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel')),
            ],
        ),
        migrations.CreateModel(
            name='BannerNewsPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.bannerconfigmodel')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_new_promo_image', to='cinema.gallerymodel')),
            ],
        ),
        migrations.CreateModel(
            name='BannerMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('text', models.CharField(max_length=50)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banner_main_page_image', to='cinema.gallerymodel')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('is_image', models.BooleanField()),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.bannerconfigmodel')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background_banner_image', to='cinema.gallerymodel')),
            ],
        ),
    ]
