# Generated by Django 4.1 on 2022-08-09 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_address_alter_usermodel_card_number_and_more'),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seomodel',
            options={'ordering': ['id'], 'verbose_name': 'СЕО модель', 'verbose_name_plural': 'СЕО модели'},
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='film_gallery', to='cinema.gallerymodel', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='main_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='film_main_image', to='cinema.gallerymodel', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='three_D',
            field=models.BooleanField(verbose_name='3D'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='two_D',
            field=models.BooleanField(verbose_name='2D'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='keywords',
            field=models.CharField(max_length=50, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.filmmodel', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.hallmodel', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='price',
            field=models.SmallIntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='three_D',
            field=models.BooleanField(verbose_name='3D'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='reservation',
            field=models.BooleanField(verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='seat',
            field=models.SmallIntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.sessionmodel', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usermodel', verbose_name='Пользователь'),
        ),
    ]
