# Generated by Django 4.1 on 2022-08-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_seomodel_options_gallerymodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallmodel',
            name='banner_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_banner_image', to='cinema.gallerymodel', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='hallmodel',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.cinemamodel', verbose_name='Кинотеатр'),
        ),
        migrations.AlterField(
            model_name='hallmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hallmodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_gallery', to='cinema.gallerymodel', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='hallmodel',
            name='hall_scheme',
            field=models.FileField(upload_to='', verbose_name='Схема зала'),
        ),
        migrations.AlterField(
            model_name='hallmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hallmodel',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seomodel', verbose_name='СЕО блок'),
        ),
    ]
