# Generated by Django 4.1 on 2022-08-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_remove_mainpagebannermodel_image_and_more'),
        ('pages', '0004_remove_mainpagemodel_seo_block_and_more'),
        ('cinema', '0003_alter_hallmodel_banner_image_alter_hallmodel_cinema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmmodel',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='filmmodel',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='filmmodel',
            name='seo_block',
        ),
        migrations.RemoveField(
            model_name='hallmodel',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='hallmodel',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='hallmodel',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='hallmodel',
            name='seo_block',
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='film',
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='ticketmodel',
            name='session',
        ),
        migrations.RemoveField(
            model_name='ticketmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CinemaModel',
        ),
        migrations.DeleteModel(
            name='FilmModel',
        ),
        migrations.DeleteModel(
            name='GalleryModel',
        ),
        migrations.DeleteModel(
            name='HallModel',
        ),
        migrations.DeleteModel(
            name='SEOModel',
        ),
        migrations.DeleteModel(
            name='SessionModel',
        ),
        migrations.DeleteModel(
            name='TicketModel',
        ),
    ]
