# Generated by Django 4.1 on 2022-08-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketModel',
        ),
    ]
